/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia2_ej04;

/**
 *
 * @author Lucas E. Sayago
 */
public class DeTodo_SA extends javax.swing.JFrame {

    /**
     * Creates new form DeTodo_SA
     */
    public DeTodo_SA() {
        initComponents();
        this.setTitle("De Todos S. A.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMConsultaPorPrecio = new javax.swing.JMenuItem();
        jMConsultaPorNombre = new javax.swing.JMenuItem();
        jMConsultaPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMProducto.setText("Producto     ");
        jMProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMProducto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMConsultaPorPrecio.setText("Precio...");
        jMenu2.add(jMConsultaPorPrecio);

        jMConsultaPorNombre.setText("Nombre...");
        jMConsultaPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaPorNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jMConsultaPorNombre);

        jMConsultaPorRubro.setText("Rubro...");
        jMenu2.add(jMConsultaPorRubro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        //dwdwdwdwdw
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMConsultaPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaPorNombreActionPerformed
        // limpiamos pantalla
        jDEscritorio.removeAll();
        
        //se redibuja
        jDEscritorio.repaint();
     
        //instanciamos un objeto del tipo de J internal Frame
     jIListadoPorNombre bpn= new jIListadoPorNombre();
     
     
     // lo hacemos visible
     bpn.setVisible(true);
     
     // agregamos al escritorio nuestro
     jDEscritorio.add(bpn);
     
     // lo pones adelante
     jDEscritorio.moveToFront(bpn);
    }//GEN-LAST:event_jMConsultaPorNombreActionPerformed

    private void jMProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProductoActionPerformed
         // limpiamos pantalla
        jDEscritorio.removeAll();
        
        //se redibuja
        jDEscritorio.repaint();
     
        //instanciamos un objeto del tipo de J internal Frame
     jIProductos bpn= new jIProductos();
     
     
     // lo hacemos visible
     bpn.setVisible(true);
     
     // agregamos al escritorio nuestro
     jDEscritorio.add(bpn);
     
     // lo pones adelante
     jDEscritorio.moveToFront(bpn);
    }//GEN-LAST:event_jMProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodo_SA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodo_SA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodo_SA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodo_SA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodo_SA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JMenuItem jMConsultaPorNombre;
    private javax.swing.JMenuItem jMConsultaPorPrecio;
    private javax.swing.JMenuItem jMConsultaPorRubro;
    private javax.swing.JMenuItem jMProducto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
